In [1]:
import pandas as pd
import numpy as np

In [2]:
def get_data(size):
    df = pd.DataFrame()
    df['age'] = np.random.randint(0, 100, size)
    df['time_spent_in_bed'] = np.random.randint(0, 9, size)
    df['pct_sleeping'] = np.random.rand(size)
    df['fav_food'] = np.random.choice(['pizzza', 'tacos', 'ice-cream'], size)
    df['hate_food'] = np.random.choice(['broccoli', 'candy corn', 'ice-eggs'], size)
    dates = pd.date_range('2020-01-01', '2022-12-31')
    df['effectve_dt'] = np.random.choice(dates, size)
    df['term_dt'] = np.random.choice(dates, size)
    df['expiration_dt'] = np.random.choice(dates, size)
    return df

In [4]:
df1 = get_data(100)
df1

,age,time_spent_in_bed,pct_sleeping,fav_food,hate_food,effectve_dt,term_dt,expiration_dt
0,16,7,0.791290,ice-cream,broccoli,2022-02-28,2021-06-29,2022-11-12
1,90,7,0.790415,pizzza,ice-eggs,2022-08-26,2021-07-02,2022-08-31
2,74,4,0.248502,tacos,broccoli,2022-10-31,2020-04-30,2022-05-18
3,91,2,0.562178,pizzza,candy corn,2020-08-26,2022-06-04,2022-02-18
4,46,0,0.214621,pizzza,candy corn,2021-12-03,2020-09-12,2020-03-31
...,...,...,...,...,...,...,...,...
95,56,4,0.962296,ice-cream,broccoli,2021-10-03,2022-03-09,2022-07-23
96,24,4,0.018555,pizzza,ice-eggs,2021-09-26,2022-08-28,2022-08-14
97,86,2,0.532551,tacos,ice-eggs,2021-11-16,2020-08-06,2022-07-07
98,56,1,0.193834,pizzza,ice-eggs,2021-11-05,2022-09-06,2021-01-28
99,88,7,0.962355,tacos,candy corn,2022-06-03,2020-09-02,2020-07-22

In [5]:
def set_dtypes(df):
    df['age'] = df['age'].astype('int16')
    df['time_spent_in_bed'] = df['time_spent_in_bed'].astype('int16')
    df['pct_sleeping'] = df['pct_sleeping'].astype('float16')
    df['fav_food'] = df['fav_food'].astype('category')
    df['hate_food'] = df['hate_food'].astype('category')
    return df

In [6]:
df2 = set_dtypes(df1)
df2

,age,time_spent_in_bed,pct_sleeping,fav_food,hate_food,effectve_dt,term_dt,expiration_dt
0,16,7,0.791504,ice-cream,broccoli,2022-02-28,2021-06-29,2022-11-12
1,90,7,0.790527,pizzza,ice-eggs,2022-08-26,2021-07-02,2022-08-31
2,74,4,0.248535,tacos,broccoli,2022-10-31,2020-04-30,2022-05-18
3,91,2,0.562012,pizzza,candy corn,2020-08-26,2022-06-04,2022-02-18
4,46,0,0.214600,pizzza,candy corn,2021-12-03,2020-09-12,2020-03-31
...,...,...,...,...,...,...,...,...
95,56,4,0.962402,ice-cream,broccoli,2021-10-03,2022-03-09,2022-07-23
96,24,4,0.018555,pizzza,ice-eggs,2021-09-26,2022-08-28,2022-08-14
97,86,2,0.532715,tacos,ice-eggs,2021-11-16,2020-08-06,2022-07-07
98,56,1,0.193848,pizzza,ice-eggs,2021-11-05,2022-09-06,2021-01-28
99,88,7,0.962402,tacos,candy corn,2022-06-03,2020-09-02,2020-07-22

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                100 non-null    int16
 1   time_spent_in_bed  100 non-null    int16
 2   pct_sleeping       100 non-null    float16
 3   fav_food           100 non-null    category
 4   hate_food          100 non-null    category
 5   effectve_dt        100 non-null    datetime64[ns]
 6   term_dt            100 non-null    datetime64[ns]
 7   expiration_dt      100 non-null    datetime64[ns]
dtypes: category(2), datetime64[ns](3), float16(1), int16(2)
memory usage: 3.5 KB